<h2>Contact</h2>

    <section>
        <p>Pour toutes questions concerant nos activités, n'hésitez pas à nous contacter. Nous vous répondrons dans les meilleurs délais.</p>
        <p>Notre écurie est situé à Welferding quartier de Sarreguemines, en Moselle. Pour une localisation éxacte référez vous au plan ci-dessous.</p>
    </section>

    <section class="contact-us">
        <h3>Nous joindre</h3>
        <address><strong>Écurie du vieux moulin</strong><br>
        Chris Schaeffer<br>
        Ferme du vieux moulin, rue de Tenteling<br>
        57200 Sarreguemines</address>
        <p id="facebook"><strong>Rejoignez nous sur facebook</strong><a href=""><i class="fab fa-facebook-square"></i></a></p>
    </section>

    <section class="contact-us">
        <h3>Nous situer</h3>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2611.690218483675!2d7.030976915921211!3d49.1115237908034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47944a62a1d06cdf%3A0x86aff614e6a61237!2sRue+de+Tenteling%2C+57200+Sarreguemines!5e0!3m2!1sfr!2sfr!4v1553518032352" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </section>
