<h2>Galerie Photos</h2>
<section class="section_galery">
    <div class="owl-carousel">
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
        <div class="item"><img src="img/DSC_0033_1.jpg" alt=""><h4>titre de l'image</h4></div>
    </div>
</section>
<section class="section_galery">
    <p>Cliquer sur une photo pour l'agrandir</p>
    <div id="galery_random">
        <a href="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" target="_blank"><img src="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" alt=""></a>
        <a href="img/240_F_80722834_j4Wp6Gs8IxOHlDZdUOGSUIFliDepi2HH.jpg" target="_blank"><img src="img/240_F_80722834_j4Wp6Gs8IxOHlDZdUOGSUIFliDepi2HH.jpg" alt=""></a>
        <a href="img/DSC_0033_1.jpg" target="_blank"><img src="img/DSC_0033_1.jpg" alt=""></a>
        <a href="img/IMG_0151.jpg" target="_blank"><img src="img/IMG_0151.jpg" alt=""></a>
        <a href="img/IMG_0153.jpg" target="_blank"><img src="img/IMG_0153.jpg" alt=""></a>
        <a href="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" target="_blank"><img src="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" alt=""></a>
    </div>
</section>
<section class="section_galery">
    <h3>Travaux éffectués</h3>
    <article>
        <ul>
            <li>
                <strong>Installation des nouveaux box</strong>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi molestiae laborum beatae commodi maxime? Laborum id eaque dolorum aspernatur harum, aperiam sunt ipsum architecto, possimus fuga libero fugiat facilis dolorem!</p>
            </li>
            <li>
                <strong>Installation du nouveau manège</strong>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi molestiae laborum beatae commodi maxime? Laborum id eaque dolorum aspernatur harum, aperiam sunt ipsum architecto, possimus fuga libero fugiat facilis dolorem!</p>
            </li>
            <li>
                <strong>Installation des nouveaux box</strong>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi molestiae laborum beatae commodi maxime? Laborum id eaque dolorum aspernatur harum, aperiam sunt ipsum architecto, possimus fuga libero fugiat facilis dolorem!</p>
            </li>
        </ul>
    </article><!--
    --><aside>
        <div class="owl-carousel">
            <div class="item"><img src="img/DSC_0033_1.jpg" alt=""></div>
            <div class="item"><img src="img/DSC_0033_1.jpg" alt=""></div>
            <div class="item"><img src="img/DSC_0033_1.jpg" alt=""></div>
        </div>
    </aside>
</section>
