<h2>Galerie Photos</h2>
<section class="section_galery">
    <div class="owl-carousel">
        <div class="item"><a href="img/DSC_0033_1.jpg" target="_blank"><img src="img/DSC_0033_1.jpg" alt=""></a><h4>Ecuries du vieux moulin</h4></div>
        <div class="item"><a href="img/29.jpg" target="_blank"><img src="img/29.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/30.jpg" target="_blank"><img src="img/30.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/7.jpg" target="_blank"><img src="img/7.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/8.jpg" target="_blank"><img src="img/8.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/9.jpg" target="_blank"><img src="img/9.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/16.jpg" target="_blank"><img src="img/16.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/21.jpg" target="_blank"><img src="img/21.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/22.jpg" target="_blank"><img src="img/22.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/24.jpg" target="_blank"><img src="img/24.jpg" alt=""></a><h4>Les parcs</h4></div>
        <div class="item"><a href="img/1.jpg" target="_blank"><img src="img/1.jpg" alt=""></a><h4>La carrière</h4></div>
        <div class="item"><a href="img/5.jpg" target="_blank"><img src="img/5.jpg" alt=""></a><h4>La carrière</h4></div>
        <div class="item"><a href="img/11.jpg" target="_blank"><img src="img/11.jpg" alt=""></a><h4>Le paddock</h4></div>
        <div class="item"><a href="img/12.jpg" target="_blank"><img src="img/12.jpg" alt=""></a><h4>Les box</h4></div>
        <div class="item"><a href="img/18.jpg" target="_blank"><img src="img/18.jpg" alt=""></a><h4>Les box</h4></div>
        <div class="item"><a href="img/23.jpg" target="_blank"><img src="img/23.jpg" alt=""></a><h4>Les box</h4></div>
        <div class="item"><a href="img/10.jpg" target="_blank"><img src="img/10.jpg" alt=""></a><h4>Le manège</h4></div>
        <div class="item"><a href="img/27.jpg" target="_blank"><img src="img/27.jpg" alt=""></a><h4>Le parking + le manège</h4></div>
        <div class="item"><a href="img/4.jpg" target="_blank"><img src="img/4.jpg" alt=""></a><h4>Le parking</h4></div>
        <div class="item"><a href="img/13.jpg" target="_blank"><img src="img/13.jpg" alt=""></a><h4>Le parking</h4></div>
        <div class="item"><a href="img/25.jpg" target="_blank"><img src="img/25.jpg" alt=""></a><h4>La piste cyclable</h4></div>


        
    </div>
</section>
<!-- <section class="section_galery">
    <p>Cliquer sur une photo pour l'agrandir</p>
    <div id="galery_random">
        <a href="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" target="_blank"><img src="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" alt=""></a>
        <a href="img/240_F_80722834_j4Wp6Gs8IxOHlDZdUOGSUIFliDepi2HH.jpg" target="_blank"><img src="img/240_F_80722834_j4Wp6Gs8IxOHlDZdUOGSUIFliDepi2HH.jpg" alt=""></a>
        <a href="img/DSC_0033_1.jpg" target="_blank"><img src="img/DSC_0033_1.jpg" alt=""></a>
        <a href="img/IMG_0151.jpg" target="_blank"><img src="img/IMG_0151.jpg" alt=""></a>
        <a href="img/IMG_0153.jpg" target="_blank"><img src="img/IMG_0153.jpg" alt=""></a>
        <a href="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" target="_blank"><img src="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" alt=""></a>
    </div>
</section> -->
<section class="section_galery">
    <h3>Travaux éffectués</h3>
    <article>
        <ul>
            <li>
                <strong>Installation des nouveaux box</strong>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi molestiae laborum beatae commodi maxime? Laborum id eaque dolorum aspernatur harum, aperiam sunt ipsum architecto, possimus fuga libero fugiat facilis dolorem!</p>
            </li>
            <li>
                <strong>Installation du nouveau manège</strong>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi molestiae laborum beatae commodi maxime? Laborum id eaque dolorum aspernatur harum, aperiam sunt ipsum architecto, possimus fuga libero fugiat facilis dolorem!</p>
            </li>
            <li>
                <strong>Installation des nouveaux box</strong>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi molestiae laborum beatae commodi maxime? Laborum id eaque dolorum aspernatur harum, aperiam sunt ipsum architecto, possimus fuga libero fugiat facilis dolorem!</p>
            </li>
        </ul>
    </article><!--
    --><aside>
        <div class="owl-carousel">
            <div class="item"><img src="img/DSC_0033_1.jpg" alt=""></div>
            <div class="item"><img src="img/DSC_0033_1.jpg" alt=""></div>
            <div class="item"><img src="img/DSC_0033_1.jpg" alt=""></div>
        </div>
    </aside>
</section>
