<h2>Acceuil</h2>
<section class="section_home">
    <p>Créé en 1963 par M. Freddy Schaeffer dans le quartier de Welferding à l'ouest de la ville de Sarreguemines, les écuries du vieux moulin vous acceuillent dans un cadre verdoyant et une ambiance familiale.</p>
    <img src="img/fond.jpg" alt="Acceuil">
    <h3>Que vous soyez cavalier de compétition ou de balade, nos installations s'adaptent à vos besoins</h3>
    <article>
        <div class="text-carousel">
            <ul>
                <li>Pour le travail des chevaux en éxterieur, vous avez à votre disposition:</li>
            </ul>
            <p><strong>une carrière</strong> de 20m x 50m,</p>
            <p><strong>un rond de longe</strong> de 18m de diamètre</p>
            <p><strong>un cross</strong> s'étendant sur 2 ha.</p>
        </div><!--
        --><div class="img-carousel">
            <div class="owl-carousel">
                <div class="item"><img src="img/IMG_0153.jpg" alt="carrière"></div>
                <div class="item"><img src="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" alt="Rond de longe"></div>
                <div class="item"><img src="img/240_F_165406266_WCT9pBsOHIHzPGaPGujrakWJbHJqsuzE.jpg" alt="Rond de longe"></div>
            </div>
        </div>
    </article>
    <article>
        <div class="text-carousel">
            <ul>
                <li>Pour le travail en intérieur, vous avez à votre disposition:</li>
            </ul>
            <p><strong>un manège</strong> de 20m x 40m qui vous permettra de travailler, peu importe les conditions climatiques.</p>
        </div><!--
        --><div class="img-carousel">
            <div class="owl-carousel"> 
                <div class="item"><img src="img/IMG_0151.jpg" alt="Manège" id="manege"></div>
                <div class="item"><img src="img/IMG_0151.jpg" alt="Manège" id="manege"></div>
                <div class="item"><img src="img/IMG_0151.jpg" alt="Manège" id="manege"></div>
            </div>
        </div>
    </article>
    <p>Pour plus d'information sur nos installations cliquez <a href="?page=installations">ici</a></p>
</section>
