<h2>Nos Installations</h2>
<section class="section_instal">
    <p><span>Que vous soyez cavalier de compétition ou de balade, nos installations <strong>s'adaptent à vos besoins</strong></span></p>
    <h3>Les écuries</h3>
    <article>
        <p>Avec vue sur le parc ou en intérieur Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque accusamus soluta asperiores obcaecati quasi, qui, hic aut voluptas ut, neque labore nisi odio consectetur quas dolores vel ex corrupti ducimus.</p>
        <img src="img/IMG_0149.jpg" alt="écuries">
    </article>
</section>
<section class="section_instal">
    <h3>Le manège</h3>
    <article>
        <p>Pour saut comme sur le plat, notre manège de 20m x 40m vous permettra de travailler votre cheval par tout les temps, sol Equi+ en sable de Fontainebleau</p>
        <img src="img/IMG_0151.jpg" alt="manège">
    </article>
</section>
<section class="section_instal">
    <h3>La carrière</h3>
    <article>
        <p>Pour le travail en extérieur, nous vous proposons une carrière de 20m x 50m où vous pourrez, dérouler une reprise ou monter votre parcours.</p>
        <img src="img/IMG_0153.jpg" alt="carrière">
    </article>
</section>
<section class="section_instal">
    <h3>Les parcs / prés / paddocks</h3>
    <article>
        <p>Pour la détente des chevaux, 6 paddocks de 300 m² accessible toute l'année, et une dizaines de prés allant de 1.000 m² à 10.000 m² ouvert d'avril à novembre sont à votre disposition.</p>
        <img src="img/30.jpg" alt="prés">
    </article>
</section>
<section class="section_instal">
    <h3>Le club house</h3>
    <article>
        <p>Disposant d'un distributeur de boissons, d'un micro-onde, d'une cafetière, d'un évier et offrant une vue sur le manège, le club house est ouvert toute la journée et vous permettra de prendre un pause</p>
        <img src="img/IMG_0153.jpg" alt="Club house">
    </article>
</section>
<section class="section_instal">
    <h3>Le terrain de cross</h3>
    <article>
        <p>Notre cross qui s'étend sur environ 2 ha vous permettra d'entrainer votre cheval au concour complet</p>
        <img src="img/IMG_0153.jpg" alt="terrain de cross">
    </article>
</section>
<section class="section_instal">
    <h3>Le rond de longe</h3>
    <article>
        <p>Pour l'échauffement de votre cheval, ou le travail à la longe, notre rond de longe de 18 mètres de diamètre et son sol Equi+ fibré</p>
        <img src="img/IMG_0153.jpg" alt="terrain de cross">
    </article>
</section>