<h2>Mentions legales</h2>
<section class="section_legal">
    <p>Responsable de la publication: Chris Schaeffer</p>
    <p>Conception et développement du site: Suler Jonathan</p>
    <p>E-mail: suler.jonathan@gmail.com</p>
    <ol>
        <li>
            <h3>Hébergement du site</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis suscipit deleniti quos eum blanditiis vel, voluptatem aliquam cum consequuntur vero nesciunt repudiandae incidunt sit, nostrum corporis in veniam voluptates eveniet?</p>
        </li>
        <li>
            <h3>Propriété intellectuelle</h3>
            <p>La structure générale, les textes, les images, graphismes, bases de données et tout autre élément composant <a href="?page=home">ecuries-du-vieux-moulin.fr</a> sont la propriété exclusive des Écuries du Vieux Moulin.<br>
L’ensemble du site relève de la législation française et internationale sur les droits d’auteur et de la propriété intellectuelle. Les noms, marques et enseignes citées sur <a href="?page=home">ecuries-du-vieux-moulin.fr</a> sont la propriété de leurs déposants respectifs. Toute utilisation ou reproduction, totale ou partielle, de <a href="?page=home">ecuries-du-vieux-moulin.fr</a>, des éléments qui composent et/ou des informations qui y figurent, par quelque procédé que ce soit, sans l’autorisation du titulaire du droit sur ces éléments sera immédiatement poursuivi, soit dans le cadre d’une action en contrefaçon, soit dans le cadre d’une action en concurrence déloyale.</p>
        </li>
        <li>
            <h3>Liens hypertextes</h3>
            <p>Les Écuries du Vieux Moulin peuvent proposer sur <a href="?page=home">ecuries-du-vieux-moulin.fr</a> des liens vers d’autres sites. La responsabilité des Écuries du Vieux Moulin ne pourra pas être engagée en rapport avec le contenu et le fonctionnement de ces sites. Les Écuries du Vieux Moulin ne pourront être tenues responsables en cas de dysfonctionnements ou de dommages causés au système informatique du visiteur.</p>
        </li>
    </ol>
</section>
