<?php if(isset($_SESSION['message'])): ?>
    <p class="message"><?= $_SESSION['message'] ?></p>
    <?php unset($_SESSION['message']) ?>
<?php endif ?>
<h2>Nos Prestations</h2>
<section>
    <img src="img/foin.jpg" id="horse_eat" alt="Nos prestations">
    <p>Aux écuries du vieux moulin, vous bénéficiez d'une prestation globale à partir de 280 €/mois* comprenant:</p>
    <ul>
        <li><strong>Le foin</strong> deux fois par jour</li>
        <li><strong>La paille</strong> une fois par semaine</li>
        <li><strong>Les granulés</strong> distribués en deux repas par jour</li>
        <li>L'accès à la <strong>totalité de nos installations</strong></li>
        <li><strong>Le curage des box</strong> une fois par semaine</li>
    </ul>
    <p>Notre offre se dinstingue en deux parties:</p>
    <p>Contrat de plus de six mois : 280€/mois</p>
    <p>Contrat de moins de six mois : 300€/mois</p>
</section>
<section class="reservation">
    <h3>Reservation</h3>
    <p>Vous avez la possibilité d'effectuer une <strong>demande de réservation de box</strong> en remplissant le formulaire ci-dessous</p>
    <p>Notre équipe mettra tout en oeuvre pour vous répondre le plus rapidement possible</p>
    <form action="#" method="POST" class="reservationForm">
        <input type="text" name="action" value="bookingBox" hidden>
        <ul>
            <li>
                <label for="lastName">Nom :</label>
                <input type="text" id="lastName" name="lastName" required>
                <span id="errorLastName"></span>
            </li>
            <li>
                <label for="firstName">Prénom :</label>
                <input type="text" id="firstName" name="firstName" required>
                <span id="errorFirstName"></span>
            </li>
        </ul>
        <ul>
            <li>
            <label for="address">Adresse :</label>
            <input type="text" id="address" name="address" required>
            <span id="errorAddress"></span>
            </li>
        </ul>
        <ul>
            <li>
                <label for="zipCode">Code postal :</label>
                <input type="text" id="zipCode" name="zipCode" maxlength="5" required>
                <span id="errorZipCode"></span>
            </li>
            <li>
                <label for="city">Ville :</label>
                <input type="text" id="city" name="city" required>
                <span id="errorCity"></span>
            </li>
        </ul>
        <ul>
            <li>
                <label for="phone">Téléphone :</label>
                <input type="phone" id="phone" name="phone" placeholder="00 00 00 00 00" maxlength="14" required>
                <span id="errorPhone"></span>
            </li>
            <li>
                <label for="email">E-mail :</label>
                <input type="email" id="email" name="email" required>
                <span id="errorEmail"></span>
            </li>
        </ul>
        <ul>
            <li>
                <label for="come">Date d'arrivée souhaitée :</label>
                <input type="date" id="come" name="come" min="<?= date('Y-m-d') ?>" required>
                <span id="errorCome"></span>
            </li>
            <li>
                <label for="contactChoice">Préférence de contact :</label>
                <select name="contactChoice" id="contactChoice">
                    <option value="phone">par téléphone</option>
                    <option value="email">par e-mail</option>
                    <option value="both">Peu importe</option>
                </select>
            </li>
            <li class="btn_confirm">
                <button type="submit" id="confirmBooking">envoyer</button>
            </li>
        </ul>
    </form>
</section>
<script src="js/check.js"></script>
