<h2>Notre Equipe</h2>
<section class="section_team">
    <article>
        <img src="img/personnel/profil.jpg" alt="Freddy Schaeffer">
        <p><strong>M. Freddy Schaeffer</strong></p>
        <p>Ancien cavalier, professionnel et instructeur, il est le fondateur des Ecuries du Vieux Moulin Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, impedit aliquam, unde distinctio voluptatem natus enim incidunt nam ullam rem dolores quasi similique. Quam distinctio aut eum repudiandae ullam adipisci.</p>
    </article>
    <article>
        <img src="img/personnel/profil.jpg" alt="Chris Schaeffer">
        <p><strong>M. Chris Schaeffer</strong></p>
        <p>Chris est l'actuel propriétaire et gérant des écuries du Vieux Moulin Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia voluptatibus illo nesciunt consequatur est aperiam expedita, nulla beatae alias magnam totam delectus quos explicabo quae sunt dolor a tenetur dolorum.</p>
    </article>
    <article>
        <img src="img/personnel/profil.jpg" alt="Rebecca Meyer">
        <p><strong>Mlle Rebecca Meyer</strong></p>
        <p>Rebecca est notre apprenti en bac professionnel CGEH Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora mollitia dignissimos fugit perspiciatis nam dolore officia repudiandae, sapiente amet nostrum temporibus ea non tenetur reiciendis voluptatibus soluta! Aut, ducimus porro?</p>
    </article>
    <h2>Nos intervenants</h2>
    <p><strong>Si vous souhaitez prendre des cours, faire travailler votre cheval, ou simplement besoin d'un conseil, nos intervenants sont à votre disposition</strong></p>
    <article>
        <img src="img/personnel/profil.jpg" alt="Nicolas Marchand">
        <p><strong>M. Nicolas Marchand</strong></p>
        <p>Moniteur diplômé depuis 2004, intervenant chez nous depuis 2011 Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi id numquam eos laudantium iusto necessitatibus assumenda animi accusamus eum repudiandae aperiam, hic distinctio, amet itaque dolorem saepe cumque suscipit sint.</p>
    </article>
    <article>
        <img src="img/personnel/profil.jpg" alt="Jonathan Arnodo">
        <p><strong>M. Jonathan Arnodo</strong></p>
        <p>Moniteur diplômé BPJEPS depuis 2009, intervenant chez nous depuis 2018 Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero molestias aut ratione, dolorem temporibus ex facere reprehenderit exercitationem nemo est repudiandae voluptate eligendi aliquid animi. Porro neque quidem tenetur blanditiis!</p>
    </article>
</section>